Appsco/appsco-applicaiton

appsco-application-add-search.html, appsco-application-add-settings.html, appsco-application-add.html, bower.json, demo/appsco-application-add.html
https://webcomputing.jira.com/browse/DASH-1820
=> DASH-1820 appsco-application-add

appsco-application-add-search.html, appsco-application-add-settings.html, bower.json
https://webcomputing.jira.com/browse/DASH-1868
=> DASH-1868 [appsco-application] Use appsco-components

appsco-application-actions.html, appsco-application-add-search.html, appsco-application-add-settings.html, appsco-application-add.html, appsco-application-details.html, appsco-application-item.html, appsco-application-log.html, appsco-application-remove.html, appsco-application-security.html, appsco-application-settings.html, appsco-application-share.html, appsco-application-subscriber.html, appsco-application-subscribers.html, appsco-applications.html, demo/appsco-application-actions.html, demo/appsco-application-add.html, demo/appsco-application-share.html, demo/appsco-application-subscribers.html
https://webcomputing.jira.com/browse/DASH-1872
=> DASH-1872 [appsco-aplication] components adaptation

appsco-application-actions.html, appsco-application-add-settings.html, appsco-application-details.html, appsco-application-log.html, appsco-application-share.html, appsco-applications.html
=> DASH-1874 [appsco-application] components

appsco-application-actions.html, appsco-application-add-search.html, appsco-application-add-settings.html, appsco-application-add.html, appsco-application-log.html, appsco-application-settings.html, appsco-application-share.html, appsco-application-subscribers.html, appsco-applications.html
=> DASH-1874 appsco-application components update

appsco-application-add-settings.html, appsco-application-item.html, appsco-applications.html
=> DASH-1874 appsco-application-add fix

appsco-application-actions.html, appsco-application-add-search.html, appsco-application-add-settings.html, appsco-application-add.html, appsco-application-item.html, appsco-application-log.html, appsco-application-remove.html, appsco-application-settings.html, appsco-application-share.html, appsco-application-subscribers.html, appsco-applications.html
=> DASH-1874 components update

appsco-application-actions.html, appsco-application-add-search.html, appsco-application-add.html, appsco-application-remove.html, appsco-application-share.html
=> DASH-1874 Style dialogs and actions in header

appsco-application-security.html
=> DASH-1874 appsco-application-security update

appsco-application-log.html
=> DASH-1874 application-components: style of appsco-application-log

appsco-application-actions.html, appsco-application-item.html, appsco-application-settings.html
=> DASH-1874 appsco-application-settings: reset method added

appsco-application-actions.html, appsco-application-subscriber.html
=> DASH-1874 appsco-application-actions style

appsco-application-actions.html
=> DASH-1874 application-actions style

appsco-applications.html
=> DASH-1874 applications container mixin added

appsco-application-add-link.html, appsco-application-add-search.html, appsco-application-add.html, appsco-application-autologin.html, appsco-application-item.html, appsco-application-log.html, appsco-application-security.html, appsco-application-settings.html, appsco-application-subscriber.html, appsco-application-subscribers.html, demo/appsco-application-log.html
https://webcomputing.jira.com/browse/DASH-1885
=> DASH-1885 polishing components

appsco-application-log.html, appsco-applications.html
https://webcomputing.jira.com/browse/DASH-1885
=> DASH-1885 appsco-application-log Type error fixed

appsco-application-item.html, appsco-application-settings.html, appsco-applications.html
https://webcomputing.jira.com/browse/DASH-1885
=> DASH-1885 appsco-applications component update

appsco-application-actions.html, appsco-application-item.html, appsco-application-share.html, appsco-applications.html
https://webcomputing.jira.com/browse/DASH-1885
=> DASH-1885 application-share, application-actions and application-item

appsco-application-security.html, demo/appsco-application-security.html
https://webcomputing.jira.com/browse/DASH-1890
=> DASH-1890 Security calculation number

appsco-application-add.html, appsco-application-details.html, appsco-application-log.html, appsco-application-remove.html, appsco-application-share.html, appsco-application-subscriber-revoke.html, appsco-applications.html, bower.json
https://webcomputing.jira.com/browse/DASH-1891
=> DASH-1891 appsco-application-log: set proper mixin names for appsco-list-item

appsco-application-add.html, appsco-application-remove.html, appsco-application-security.html, appsco-application-share.html, appsco-application-subscriber-revoke.html
https://webcomputing.jira.com/browse/DASH-1891
=> DASH-1891 paper-dialogs responsive

appsco-application-sharing-settings.html, appsco-applications.html, demo/appsco-application-sharing-settings.html
https://webcomputing.jira.com/browse/DASH-1909
=> DASH-1909 appsco-application-sharing-settings

appsco-application-analytics-info.html, appsco-application-details.html, appsco-application.html, demo/appsco-application-analytics-info.html
https://webcomputing.jira.com/browse/DASH-1899
=> DASH-1899 appsco-application-analytics-info

appsco-application-actions.html, demo/appsco-application-actions.html
https://webcomputing.jira.com/browse/DASH-1897
=> DASH-1897 [appsco-applications-actions] extend with bulk actions

appsco-application-analytics-security.html, appsco-application-security.html, appsco-application.html, demo/appsco-application-analytics-security.html
https://webcomputing.jira.com/browse/DASH-1898
=> DASH-1898 appsco-application-analytics-security

appsco-application-analytics-info.html, appsco-application-analytics-security.html, appsco-application-info.html, appsco-application-item.html, appsco-applications.html, demo/appsco-application-analytics-security.html
https://webcomputing.jira.com/browse/DASH-1895
=> DASH-1895 appsco-applications-page (management)

appsco-application-analytics-info.html, appsco-application-analytics-security.html, appsco-application-item.html, appsco-application-log.html, appsco-application-subscribers.html, appsco-applications.html, demo/appsco-application-analytics-info.html, demo/appsco-application-analytics-security.html
https://webcomputing.jira.com/browse/DASH-1895
=> DASH-1895 appsco-application-analytics-info

appsco-application-actions.html, appsco-application-analytics-info.html, appsco-application-item.html, appsco-application.html, appsco-applications.html, bower.json, company/appsco-application-orgunit.html, demo/company/appsco-application-orgunit.html
https://webcomputing.jira.com/browse/DASH-1925
=> DASH-1925 appsco-application-orgunit

appsco-application-actions.html, appsco-application-add-search.html, appsco-application-add.html, appsco-application-details.html, appsco-application-log.html, appsco-application-settings.html, appsco-application-share.html, appsco-application-sharing-settings.html, appsco-application-subscribers.html, appsco-application.html, company/appsco-application-orgunit-item.html, company/appsco-application-orgunit.html, company/appsco-application-orgunits.html, company/appsco-application-remove-orgunit.html, company/appsco-company-application-add.html, company/appsco-company-application-share.html, demo/appsco-application-sharing-settings.html
https://webcomputing.jira.com/browse/DASH-1908
=> DASH-1908 appsco-application-page (management) components

appsco-application-analytics-security.html
https://webcomputing.jira.com/browse/DASH-1925
=> DASH-1925 components update

appsco-application-analytics-security.html, appsco-application.html, company/appsco-application-assignee-claims.html, company/appsco-application-assignee-revoke.html, company/appsco-application-assignee.html, company/appsco-application-assignees.html, company/appsco-company-application-remove.html
https://webcomputing.jira.com/browse/DASH-1908
=> DASH-1908 company: appsco-application-assignees

appsco-application-actions.html, appsco-application-details.html, appsco-applications.html, company/appsco-application-assignee-claims.html, company/appsco-application-assignee-revoke.html, company/appsco-application-assignee.html, company/appsco-application-assignees.html, company/appsco-application-orgunit-item.html, company/appsco-application-orgunit.html, company/appsco-application-orgunits.html, company/appsco-application-remove-orgunit.html, company/appsco-company-application-remove.html, company/appsco-company-application-share.html, demo/company/appsco-application-assignee-claims.html, demo/company/appsco-application-assignee-revoke.html, demo/company/appsco-application-assignee.html, demo/company/appsco-application-assignees.html, demo/company/appsco-application-orgunits.html, demo/company/appsco-application-remove-orgunit.html, demo/company/appsco-company-application-remove.html, demo/company/appsco-company-application-share.html
https://webcomputing.jira.com/browse/DASH-1908
=> DASH-1908 appsco-application-page components update

appsco-application-actions.html, appsco-application-add-link.html, appsco-application-add.html, appsco-application-log.html, appsco-application-subscribers.html, company/appsco-application-assignees.html
https://webcomputing.jira.com/browse/DASH-1962
https://webcomputing.jira.com/browse/DASH-1943
https://webcomputing.jira.com/browse/DASH-1944
=> DASH-1962 appsco-application: load subscribers and log

appsco-application-actions.html, appsco-application-add-link.html, appsco-application-add-search.html, appsco-application-add-settings.html, appsco-application-add.html, appsco-application-analytics-info.html, appsco-application-log.html, appsco-application-remove.html, appsco-application-share.html, appsco-application-subscribers.html, appsco-applications.html, company/appsco-application-assignee-claims.html, company/appsco-application-assignees.html, company/appsco-application-orgunit.html, company/appsco-application-orgunits.html, company/appsco-application-remove-orgunit.html, company/appsco-company-application-add.html, company/appsco-company-application-remove.html, company/appsco-company-application-share.html
https://webcomputing.jira.com/browse/DASH-1973
https://webcomputing.jira.com/browse/DASH-1963
=> DASH-1973 paper-dialog-scrollable: scroll is always present

company/appsco-application-assignees.html, company/appsco-company-application-share.html
https://webcomputing.jira.com/browse/DASH-1933
=> DASH-1933 Application not assigned

appsco-application-add-link.html, appsco-application-add-search.html, appsco-application-add.html
https://webcomputing.jira.com/browse/DASH-1963
=> DASH-1963 Unable to add custom item

appsco-applications.html
https://webcomputing.jira.com/browse/DASH-1988
=> DASH-1988 [Company] Filter applications and accounts by organization unit

appsco-application-subscriber.html, appsco-application-subscribers.html, company/appsco-application-assignee.html
https://webcomputing.jira.com/browse/DASH-1984
=> DASH-1984 Initials set on subscribers

appsco-application-log.html
https://webcomputing.jira.com/browse/DASH-1991
=> DASH-1991 [Application] Update application log with new log types

appsco-applications.html
https://webcomputing.jira.com/browse/DASH-2010
=> DASH-2010 Load more applications

appsco-application-analytics-info.html, appsco-application-autologin.html, appsco-application-details.html
https://webcomputing.jira.com/browse/DASH-2061
=> DASH-2061 [appsco-application] appsco-application-analytics-info component update

appsco-application-actions.html, appsco-applications.html
https://webcomputing.jira.com/browse/DASH-2073
=> DASH-2073 Create dashboard if private does not exist

appsco-account-card.html, appsco-application-share.html, company/appsco-company-application-share.html
https://webcomputing.jira.com/browse/DASH-2042
=> DASH-2042 Share app - Not able to distinguish users with same name but different emails

appsco-account-card.html, appsco-application-actions.html, appsco-application-item.html, appsco-applications.html, company/appsco-application-assignees.html
https://webcomputing.jira.com/browse/DASH-2037
=> DASH-2037 Filter applications + select applications bug

appsco-application-log.html, appsco-application-subscribers.html, appsco-applications.html, company/appsco-application-assignees.html
https://webcomputing.jira.com/browse/DASH-2101
=> DASH-2101 Make faster lists loading within pages

appsco-application-subscriber.html, appsco-application-subscribers.html, appsco-applications.html, company/appsco-application-assignee.html, company/appsco-application-assignees.html
https://webcomputing.jira.com/browse/DASH-2058
=> DASH-2058 Implement search on assignees list - frontend

appsco-application-actions.html, appsco-applications.html
https://webcomputing.jira.com/browse/DASH-2118
=> DASH-2118 [HOME] Search Applications by term

appsco-applications.html
https://webcomputing.jira.com/browse/DASH-2118
=> DASH-2118 Search Applications by term - load more fix

appsco-application-settings.html
https://webcomputing.jira.com/browse/DASH-2137
=> DASH-2137 Edit credentials button on Free users apps

appsco-applications.html, company/appsco-company-application-remove.html
https://github.com/Appsco/appsco-front/pull/105
=> DASH-2177 [Personal] Application info sending to 404

appsco-application-actions.html
https://webcomputing.jira.com/browse/DASH-2154
=> DASH-2154 [Front] Apply company branding within pages

appsco-application-remove.html
https://webcomputing.jira.com/browse/DASH-2215
=> DASH-2215 [Application Page] Subscribers preview on application remove

appsco-application-actions.html
https://webcomputing.jira.com/browse/DASH-2226
=> DASH-2226 Issues after removing org-unit

appsco-application.html, appsco-applications.html, company/appsco-company-application-add-search.html, company/appsco-company-application-add-settings.html, company/appsco-company-application-add.html
https://webcomputing.jira.com/browse/DASH-2276
=> DASH-2276 No link or custom application for company applications

appsco-application-actions.html, appsco-application-add-search.html, appsco-application-share.html, company/appsco-company-application-add-search.html, company/appsco-company-application-add-settings.html, company/appsco-company-application-add.html, company/appsco-company-application-share.html
https://webcomputing.jira.com/browse/DASH-2253
=> DASH-2253 [Frontend] Improve input search field event through project

appsco-application-subscribers.html, company/appsco-application-assignee.html, company/appsco-application-assignees.html
https://webcomputing.jira.com/browse/DASH-2300
=> DASH-2300 [Business] Unable to load assigness

appsco-application-item.html, appsco-application-settings.html, appsco-application-sharing-settings.html, appsco-applications.html
https://webcomputing.jira.com/browse/DASH-2272
=> DASH-2272 Implement branding text colours when card is selected

appsco-application-sharing-settings.html, company/appsco-application-assignee-claims.html
https://webcomputing.jira.com/browse/DASH-2282
=> DASH-2282 Problem with adding Items to setup credidentials

appsco-application-sharing-settings.html
https://webcomputing.jira.com/browse/DASH-2282
=> DASH-2282 Claims: username and password are required

appsco-applications.html
https://webcomputing.jira.com/browse/DASH-2342
=> DASH-2342 [Frontend] First application not showing up

appsco-application-actions.html
https://webcomputing.jira.com/browse/DASH-2124
=> DASH-2124 Add resource action

appsco-applications.html
https://webcomputing.jira.com/browse/DASH-2355
=> DASH-2355 Double applications showing up

appsco-application-actions.html
Reverts Appsco/appsco-applicaiton#70
=> Revert "DASH-2124 Add resource action"

appsco-application-log.html
https://webcomputing.jira.com/browse/DASH-2353
=> DASH-2353 [Frontend][Application Log] Sharing free and company application should create different log types

appsco-application-actions.html
https://webcomputing.jira.com/browse/DASH-2264
=> DASH-2264 [Frontend]Home] Filtering applications

appsco-application-details-unpw.html, appsco-application-details.html
https://webcomputing.jira.com/browse/DASH-2246
=> DASH-2246 [Frontend][Audit Log] Implement new log event type

company/appsco-application-assignees.html
https://webcomputing.jira.com/browse/DASH-2372
=> DASH-2372 [Frontend][Applications] - Assignees not reflecting org unit changes

appsco-application-sharing-settings.html
https://webcomputing.jira.com/browse/DASH-2375
=> DASH-2375 [Frontend][Application] - Sharing settings
